// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 Gracker (Chris)
// This file is part of SmartPerfetto. See LICENSE for details.

import type Database from 'better-sqlite3';
import type {
  AnalysisResultSceneType,
  AnalysisResultWindowState,
} from '../types/multiTraceComparison';
import type { EnterpriseRepositoryScope } from './enterpriseRepository';
import { readableClause as readableSnapshotClause } from './analysisResultSnapshotStore';

const DEFAULT_WINDOW_STATE_TTL_MS = 2 * 60 * 1000;

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

interface WindowStateRow {
  tenant_id: string;
  workspace_id: string;
  window_id: string;
  user_id: string;
  trace_id: string | null;
  backend_trace_id: string | null;
  active_session_id: string | null;
  latest_snapshot_id: string | null;
  trace_title: string | null;
  scene_type: AnalysisResultSceneType | null;
  metadata_json: string | null;
  updated_at: number;
  expires_at: number;
}

/**
 * Window ids are generated by the browser and listed to every reader of the
 * workspace, so they identify a window only within its owner's namespace: the
 * owner always comes from the authenticated scope, never from the request.
 */
export interface AnalysisResultWindowHeartbeatInput {
  windowId: string;
  traceId?: string;
  backendTraceId?: string;
  activeSessionId?: string;
  latestSnapshotId?: string;
  traceTitle?: string;
  sceneType?: AnalysisResultSceneType;
  metadata?: Record<string, JsonValue>;
  ttlMs?: number;
}

export interface ListActiveWindowStateOptions {
  excludeWindowId?: string;
  limit?: number;
  now?: number;
}

export interface UpsertWindowStateOptions {
  ensureScopeGraph?: boolean;
}

function parseJson<T>(value: string | null, fallback: T): T {
  if (!value) return fallback;
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

function optionalText(value: string | undefined): string | null {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

function boundedLimit(limit: number | undefined): number {
  if (limit === undefined) return 20;
  if (!Number.isInteger(limit) || limit < 1 || limit > 100) {
    throw new Error('limit must be an integer between 1 and 100');
  }
  return limit;
}

function ttlFromInput(ttlMs: number | undefined): number {
  if (ttlMs === undefined) return DEFAULT_WINDOW_STATE_TTL_MS;
  if (!Number.isFinite(ttlMs) || ttlMs < 15_000 || ttlMs > 10 * 60 * 1000) {
    throw new Error('ttlMs must be between 15000 and 600000');
  }
  return Math.floor(ttlMs);
}

function requireScopeUserId(scope: EnterpriseRepositoryScope): string {
  const userId = scope.userId?.trim();
  if (!userId) {
    throw new Error('Analysis result window state requires an authenticated user');
  }
  return userId;
}

function ensureWindowStateScopeGraph(
  db: Database.Database,
  scope: EnterpriseRepositoryScope,
  userId: string,
  now: number,
): void {
  db.prepare(`
    INSERT OR IGNORE INTO organizations (id, name, status, plan, created_at, updated_at)
    VALUES (?, ?, 'active', 'enterprise', ?, ?)
  `).run(scope.tenantId, scope.tenantId, now, now);

  db.prepare(`
    INSERT OR IGNORE INTO workspaces (id, tenant_id, name, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?)
  `).run(scope.workspaceId, scope.tenantId, scope.workspaceId, now, now);

  db.prepare(`
    INSERT INTO users (id, tenant_id, email, display_name, idp_subject, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      email = excluded.email,
      display_name = excluded.display_name,
      updated_at = excluded.updated_at
  `).run(
    userId,
    scope.tenantId,
    `${userId}@window-state.local`,
    userId,
    `window-state:${userId}`,
    now,
    now,
  );
}

/**
 * Another user's window is shown only as a pointer to an analysis result the
 * reader may already read; its trace, session and free-form fields stay with
 * its owner.
 */
function mapPeerWindowState(row: WindowStateRow): AnalysisResultWindowState {
  return {
    tenantId: row.tenant_id,
    workspaceId: row.workspace_id,
    windowId: row.window_id,
    userId: row.user_id,
    ...(row.latest_snapshot_id ? { latestSnapshotId: row.latest_snapshot_id } : {}),
    ...(row.scene_type ? { sceneType: row.scene_type } : {}),
    metadata: {},
    updatedAt: row.updated_at,
    expiresAt: row.expires_at,
  };
}

function mapWindowState(row: WindowStateRow): AnalysisResultWindowState {
  return {
    ...mapPeerWindowState(row),
    ...(row.trace_id ? { traceId: row.trace_id } : {}),
    ...(row.backend_trace_id ? { backendTraceId: row.backend_trace_id } : {}),
    ...(row.active_session_id ? { activeSessionId: row.active_session_id } : {}),
    ...(row.trace_title ? { traceTitle: row.trace_title } : {}),
    metadata: parseJson<Record<string, unknown>>(row.metadata_json, {}),
  };
}

export class AnalysisResultWindowStateRepository {
  constructor(private readonly db: Database.Database) {}

  scopeGraphExists(scope: EnterpriseRepositoryScope): boolean {
    const row = this.db.prepare(`
      SELECT 1
      FROM organizations o
      JOIN workspaces w
        ON w.tenant_id = o.id
       AND w.id = @workspaceId
      WHERE o.id = @tenantId
      LIMIT 1
    `).get({
      tenantId: scope.tenantId,
      workspaceId: scope.workspaceId,
    });
    return Boolean(row);
  }

  upsertWindowState(
    scope: EnterpriseRepositoryScope,
    input: AnalysisResultWindowHeartbeatInput,
    options: UpsertWindowStateOptions = {},
  ): AnalysisResultWindowState {
    const userId = requireScopeUserId(scope);
    const persist = this.db.transaction((): AnalysisResultWindowState => {
      const now = Date.now();
      if (options.ensureScopeGraph) {
        ensureWindowStateScopeGraph(this.db, scope, userId, now);
      }

      const ttlMs = ttlFromInput(input.ttlMs);
      const params = {
        tenantId: scope.tenantId,
        workspaceId: scope.workspaceId,
        windowId: input.windowId,
        userId,
        traceId: optionalText(input.traceId),
        backendTraceId: optionalText(input.backendTraceId),
        activeSessionId: optionalText(input.activeSessionId),
        latestSnapshotId: optionalText(input.latestSnapshotId),
        traceTitle: optionalText(input.traceTitle),
        sceneType: optionalText(input.sceneType),
        metadataJson: JSON.stringify(input.metadata ?? {}),
        updatedAt: now,
        expiresAt: now + ttlMs,
      };

      this.db.prepare(`
        INSERT INTO analysis_result_window_states
          (tenant_id, workspace_id, window_id, user_id, trace_id, backend_trace_id,
           active_session_id, latest_snapshot_id, trace_title, scene_type,
           metadata_json, updated_at, expires_at)
        VALUES
          (@tenantId, @workspaceId, @windowId, @userId, @traceId, @backendTraceId,
           @activeSessionId, @latestSnapshotId, @traceTitle, @sceneType,
           @metadataJson, @updatedAt, @expiresAt)
        ON CONFLICT(tenant_id, workspace_id, user_id, window_id) DO UPDATE SET
          trace_id = excluded.trace_id,
          backend_trace_id = excluded.backend_trace_id,
          active_session_id = excluded.active_session_id,
          latest_snapshot_id = excluded.latest_snapshot_id,
          trace_title = excluded.trace_title,
          scene_type = excluded.scene_type,
          metadata_json = excluded.metadata_json,
          updated_at = excluded.updated_at,
          expires_at = excluded.expires_at
      `).run(params);

      const state = this.getWindowState(scope, input.windowId);
      if (!state) {
        throw new Error('Failed to persist analysis result window state');
      }
      return state;
    });
    return persist();
  }

  getWindowState(
    scope: EnterpriseRepositoryScope,
    windowId: string,
  ): AnalysisResultWindowState | null {
    const row = this.db.prepare<unknown[], WindowStateRow>(`
      SELECT *
      FROM analysis_result_window_states
      WHERE tenant_id = @tenantId
        AND workspace_id = @workspaceId
        AND user_id = @userId
        AND window_id = @windowId
      LIMIT 1
    `).get({
      tenantId: scope.tenantId,
      workspaceId: scope.workspaceId,
      userId: requireScopeUserId(scope),
      windowId,
    });
    return row ? mapWindowState(row) : null;
  }

  /**
   * The reader's own windows in full, and other users' windows whose latest
   * analysis result the reader can read, projected by `mapPeerWindowState`.
   */
  listActiveWindowStates(
    scope: EnterpriseRepositoryScope,
    options: ListActiveWindowStateOptions = {},
  ): AnalysisResultWindowState[] {
    const userId = requireScopeUserId(scope);
    // The snapshot store owns who may read a result; its clause and its own
    // parameters are reused verbatim (alias `s`) so a peer window never
    // outlives that rule. The window clauses bind separately named
    // parameters so they stay independent of the clause's parameter names.
    const readable = readableSnapshotClause({ ...scope, userId });
    const clauses = [
      'w.tenant_id = @windowTenantId',
      'w.workspace_id = @windowWorkspaceId',
      'w.expires_at > @now',
      `(w.user_id = @ownerUserId OR EXISTS (
        SELECT 1 FROM analysis_result_snapshots s
        WHERE s.id = w.latest_snapshot_id AND ${readable.sql}
      ))`,
    ];
    const params: Record<string, string | number | null> = {
      ...readable.params,
      windowTenantId: scope.tenantId,
      windowWorkspaceId: scope.workspaceId,
      ownerUserId: userId,
      now: options.now ?? Date.now(),
      limit: boundedLimit(options.limit),
    };
    if (options.excludeWindowId) {
      clauses.push('NOT (w.user_id = @ownerUserId AND w.window_id = @excludeWindowId)');
      params.excludeWindowId = options.excludeWindowId;
    }

    return this.db.prepare<unknown[], WindowStateRow>(`
      SELECT w.*
      FROM analysis_result_window_states w
      WHERE ${clauses.join(' AND ')}
      ORDER BY w.updated_at DESC, w.user_id ASC, w.window_id ASC
      LIMIT @limit
    `).all(params).map(row => (
      row.user_id === userId ? mapWindowState(row) : mapPeerWindowState(row)
    ));
  }
}

export function createAnalysisResultWindowStateRepository(
  db: Database.Database,
): AnalysisResultWindowStateRepository {
  return new AnalysisResultWindowStateRepository(db);
}
