// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 Gracker (Chris)
// This file is part of SmartPerfetto. See LICENSE for details.

/**
 * Unified Session State Snapshot
 *
 * Single source of truth for persistence, report generation, and session restoration.
 * Replaces the fragile 7-phase persistence cascade (7 sequential read-modify-write
 * cycles on the same SQLite metadata JSON blob) with one atomic write.
 *
 * Written at analysis completion; read by resume, report, and SSE reconnect paths.
 *
 * Key invariants:
 * 1. Snapshot is the single source of truth for report generation — never assemble
 *    from live getters + fallback chains.
 * 2. Snapshot is written atomically — one UPDATE metadata call, not 6+ sequential RMW.
 * 3. All restoration paths read the same snapshot — resume, report, SSE reconnect.
 * 4. ClaudeRuntime Maps = live cache; snapshot = durable copy.
 * 5. Backward compatibility through dual-write — no breaking changes for old sessions.
 */

import type { AnalysisNote, AnalysisPlanV3, Hypothesis, UncertaintyFlag } from './types';
import type { StoredArtifact } from './artifactStore';
import type { ArchitectureInfo } from '../agent/detectors/types';
import type { DataEnvelope } from '../types/dataContract';
import type { ClaimSupportV1 } from '../types/evidenceContract';
import type { ClaimVerificationResult } from '../types/claimVerification';
import type { IdentityResolutionV1 } from '../types/identityContract';
import type { CodeAwareMode } from '../services/codebase/codeAwareFeature';
import type { CodeLookupSummary } from '../services/codebase/codeLookupLedger';
import {
  sanitizeSourceUseDecision,
  type SourceUseDecisionV1,
} from '../services/codebase/sourceUseDecision';
import type { AgentRuntimeKind } from '../services/providerManager/types';
import type {OutputLanguage} from './outputLanguage';
import {analysisHasPrivateContext, privateContextRestrictsAudience} from '../services/security/analysisPrivateContext';
import type {AnalysisPrivateContextMarker} from '../services/security/analysisPrivateContext';

export type ComparisonSourceKind = 'raw_trace_pair' | 'analysis_result_snapshots';

export interface ComparisonReportSection {
  source: ComparisonSourceKind;
  title: string;
  markdown: string;
  html: string;
  limitations?: string[];
  evidencePack?: unknown;
}

// =============================================================================
// Typed sub-interfaces — replace inline anonymous types from AnalysisSession
// =============================================================================

/** A step in the conversation timeline (SSE event log). */
export interface ConversationStep {
  eventId: string;
  ordinal: number;
  phase: 'progress' | 'thinking' | 'tool' | 'result' | 'error';
  role: 'agent' | 'system';
  text: string;
  timestamp: number;
  sourceEventType?: string;
}

/** A query submitted by the user in a specific turn. */
export interface QueryHistoryEntry {
  turn: number;
  query: string;
  timestamp: number;
}

/** A conclusion generated by the agent after a specific turn. */
export interface ConclusionHistoryEntry {
  turn: number;
  conclusion: string;
  confidence: number;
  timestamp: number;
}

/** An inter-agent dialogue entry (task dispatch / response / question). */
export interface AgentDialogueEntry {
  agentId: string;
  type: 'task' | 'response' | 'question';
  content: any;
  timestamp: number;
}

/** A response from a sub-agent task. */
export interface AgentResponseEntry {
  taskId: string;
  agentId: string;
  response: any;
  timestamp: number;
}

export interface SnapshotRunContext {
  runId: string;
  requestId: string;
  sequence: number;
  query: string;
  startedAt: number;
  completedAt?: number;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'quota_exceeded';
  error?: string;
  /** Fixed at admission; absent on runs serialized before markers existed. */
  privateContext?: AnalysisPrivateContextMarker;
}

export interface SnapshotEngineProviderState {
  /** Provider profile that supplied runtime credentials; null means env/default fallback. */
  providerId?: string | null;
  /** Non-secret provider/runtime snapshot hash for SDK state reuse checks. */
  providerSnapshotHash?: string | null;
}

export type ProviderContinuityBreakReason = 'provider_snapshot_hash_mismatch';

export interface ProviderContinuityBreak {
  at: number;
  previousProviderHash: string;
  reason: ProviderContinuityBreakReason;
}

function isProviderContinuityBreak(value: unknown): value is ProviderContinuityBreak {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const candidate = value as Partial<ProviderContinuityBreak>;
  return typeof candidate.at === 'number'
    && Number.isFinite(candidate.at)
    && typeof candidate.previousProviderHash === 'string'
    && candidate.previousProviderHash.length > 0
    && candidate.reason === 'provider_snapshot_hash_mismatch';
}

/**
 * The valid continuity-break audit carried by a persisted snapshot, plus one
 * entry when this restore found the provider snapshot changed from
 * `changedFromProviderHash`. Every restore path must carry it forward, because
 * the next persisted snapshot is written from the live session.
 */
export function continuityBreaksAfterRestore(
  existing: unknown,
  changedFromProviderHash: string | null | undefined,
): ProviderContinuityBreak[] {
  const breaks = Array.isArray(existing) ? existing.filter(isProviderContinuityBreak) : [];
  if (!changedFromProviderHash) return breaks;
  return [
    ...breaks,
    {at: Date.now(), previousProviderHash: changedFromProviderHash, reason: 'provider_snapshot_hash_mismatch'},
  ];
}

export type SessionLineageReason = 'cli-level3-degraded';

export interface SessionLineage {
  previousBackendSessionId: string;
  reason: SessionLineageReason;
  at: number;
}

/**
 * Shape of legacy stored content only. Claude runs start from fresh physical
 * context, write `{}` here and never read the SDK session id back.
 */
interface ClaudeSnapshotEngineState {
  sdkSessionId?: string;
  sdkSessionMode?: 'full';
}

/**
 * Shape of legacy stored content only. OpenAI runs start from fresh physical
 * context, write `{}` here and never read these fields back.
 */
export interface OpenAISnapshotEngineState {
  history?: unknown[];
  lastResponseId?: string;
  runState?: string;
}

type ThirdPartyOpaqueDegradedReason =
  | 'missing_required_fields'
  | 'state_unavailable'
  | 'session_restore_failed';

interface PiAgentCoreOpaqueState {
  version: 1;
  messages?: unknown[];
  messageCount: number;
  originalMessageCount?: number;
  truncated?: boolean;
  byteSize?: number;
  degradedReason?: 'not_json_serializable' | 'too_large';
}

interface OpenCodeOpaqueState {
  version: 1;
  openCodeSessionId?: string;
  projectDir?: string;
  homeDir?: string;
  configDir?: string;
  degradedReason?: ThirdPartyOpaqueDegradedReason;
}

/**
 * Shape of legacy stored content only. Pi runs start from fresh physical
 * context, write `{}` here and never read the transcript back.
 */
interface PiAgentCoreSnapshotEngineState {
  opaque?: PiAgentCoreOpaqueState;
}

/**
 * Shape of legacy stored content only. OpenCode runs create a fresh native
 * session in directories derived from the SmartPerfetto session id, write `{}`
 * here and never read the stored session id or directories back.
 */
interface OpenCodeSnapshotEngineState {
  opaque?: OpenCodeOpaqueState;
}

interface QoderOpaqueState {
  version: 1;
  sdkSessionId?: string;
  degradedReason?: ThirdPartyOpaqueDegradedReason;
}

/**
 * Shape of legacy stored content only. Qoder runs start from fresh physical
 * context, write `{}` here and never read the SDK session id back.
 */
interface QoderSnapshotEngineState {
  opaque?: QoderOpaqueState;
}

export type SnapshotEngineState =
  | {
      kind: 'claude-agent-sdk';
      provider: SnapshotEngineProviderState;
      claude: ClaudeSnapshotEngineState;
      openai?: never;
      pi?: never;
    }
  | {
      kind: 'openai-agents-sdk';
      provider: SnapshotEngineProviderState;
      openai: OpenAISnapshotEngineState;
      claude?: never;
      pi?: never;
    }
  | {
      kind: 'pi-agent-core';
      provider: SnapshotEngineProviderState;
      pi: PiAgentCoreSnapshotEngineState;
      claude?: never;
      openai?: never;
      opencode?: never;
    }
  | {
      kind: 'opencode';
      provider: SnapshotEngineProviderState;
      opencode: OpenCodeSnapshotEngineState;
      claude?: never;
      openai?: never;
      pi?: never;
    }
  | {
      kind: 'qoder-agent-sdk';
      provider: SnapshotEngineProviderState;
      qoder: QoderSnapshotEngineState;
      claude?: never;
      openai?: never;
      pi?: never;
      opencode?: never;
    };

interface EngineProviderStateInput {
  providerId?: string | null;
  providerSnapshotHash?: string | null;
}

function createSnapshotEngineProviderState(
  input: EngineProviderStateInput,
): SnapshotEngineProviderState {
  return {
    providerId: input.providerId ?? null,
    providerSnapshotHash: input.providerSnapshotHash ?? null,
  };
}

export function createClaudeSnapshotEngineState(
  input: EngineProviderStateInput,
): SnapshotEngineState {
  return {
    kind: 'claude-agent-sdk',
    provider: createSnapshotEngineProviderState(input),
    claude: {},
  };
}

export function createOpenAISnapshotEngineState(
  input: EngineProviderStateInput,
): SnapshotEngineState {
  return {
    kind: 'openai-agents-sdk',
    provider: createSnapshotEngineProviderState(input),
    openai: {},
  };
}

export function createPiAgentCoreSnapshotEngineState(
  input: EngineProviderStateInput = {},
): SnapshotEngineState {
  return {
    kind: 'pi-agent-core',
    provider: createSnapshotEngineProviderState(input),
    pi: {},
  };
}

export function createOpenCodeSnapshotEngineState(
  input: EngineProviderStateInput = {},
): SnapshotEngineState {
  return {
    kind: 'opencode',
    provider: createSnapshotEngineProviderState(input),
    opencode: {},
  };
}

export function createQoderSnapshotEngineState(
  input: EngineProviderStateInput = {},
): SnapshotEngineState {
  return {
    kind: 'qoder-agent-sdk',
    provider: createSnapshotEngineProviderState(input),
    qoder: {},
  };
}

export function getSnapshotRuntimeKind(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'agentRuntimeKind'> | null | undefined,
): AgentRuntimeKind | undefined {
  return snapshot?.engineState?.kind ?? snapshot?.agentRuntimeKind;
}

export function getSnapshotRuntimeProviderId(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'agentRuntimeProviderId'> | null | undefined,
): string | null | undefined {
  const provider = snapshot?.engineState?.provider;
  if (provider && Object.prototype.hasOwnProperty.call(provider, 'providerId')) {
    return provider.providerId ?? null;
  }
  return snapshot?.agentRuntimeProviderId;
}

export function getSnapshotRuntimeProviderSnapshotHash(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'agentRuntimeProviderSnapshotHash'> | null | undefined,
): string | null | undefined {
  const provider = snapshot?.engineState?.provider;
  if (provider && Object.prototype.hasOwnProperty.call(provider, 'providerSnapshotHash')) {
    return provider.providerSnapshotHash ?? null;
  }
  return snapshot?.agentRuntimeProviderSnapshotHash;
}

/**
 * Whether a persisted session proves it carries no private context, so its
 * runtime state may be restored. Its runs' fixed markers decide. A snapshot
 * without run markers (one written before markers existed, and every private
 * snapshot, whose projection drops its runs) must record its fingerprint,
 * which dates it after the selection was recorded in full, and a selection
 * without private material. Everything else (a restricted, unknown or
 * malformed marker, an older or rebuilt snapshot, no snapshot) is not
 * restorable.
 */
export function snapshotProvesNoPrivateContext(
  snapshot: Pick<SessionStateSnapshot, 'activeRun' | 'lastRun' | 'analysisContextFingerprint' |
    'codeAwareMode' | 'codebaseIds' | 'knowledgeSourceIds'> | null | undefined,
): boolean {
  if (!snapshot) return false;
  const runs: unknown[] = [snapshot.activeRun, snapshot.lastRun].filter(run => run !== undefined && run !== null);
  if (!runs.every((run): run is SnapshotRunContext => typeof run === 'object')) return false;
  // Once any run carries a marker, every run must: one public run cannot
  // vouch for another whose marker is missing.
  if (runs.some(run => 'privateContext' in run)) return runs.every(run => !privateContextRestrictsAudience(run.privateContext));
  return Boolean(snapshot.analysisContextFingerprint) && !analysisHasPrivateContext(snapshot);
}

function normalizeSourceUseSnapshotFields(
  rawSourceUseDecision: unknown,
  rawCodeLookupSummary: CodeLookupSummary | undefined,
  currentSelectedCodebaseIds: readonly string[],
): {
  sourceUseDecision?: SourceUseDecisionV1;
  codeLookupSummary?: CodeLookupSummary;
} {
  const summaryDecision = sanitizeSourceUseDecision(
    rawCodeLookupSummary?.sourceUseDecision,
    currentSelectedCodebaseIds,
  );
  const sourceUseDecision = sanitizeSourceUseDecision(
    rawSourceUseDecision,
    currentSelectedCodebaseIds,
  ) ?? summaryDecision;
  if (!rawCodeLookupSummary) {
    return sourceUseDecision ? {sourceUseDecision} : {};
  }
  const {
    sourceUseDecision: _rawSummaryDecision,
    ...summaryWithoutSourceUse
  } = rawCodeLookupSummary;
  return {
    ...(sourceUseDecision ? {sourceUseDecision} : {}),
    codeLookupSummary: {
      ...summaryWithoutSourceUse,
      ...(sourceUseDecision ? {sourceUseDecision} : {}),
    },
  };
}

/** Every runtime's engine state now holds only its provider pin. */
const PROVIDER_ONLY_ENGINE_STATE: Record<
  AgentRuntimeKind,
  (input: EngineProviderStateInput) => SnapshotEngineState
> = {
  'claude-agent-sdk': createClaudeSnapshotEngineState,
  'openai-agents-sdk': createOpenAISnapshotEngineState,
  'pi-agent-core': createPiAgentCoreSnapshotEngineState,
  'opencode': createOpenCodeSnapshotEngineState,
  'qoder-agent-sdk': createQoderSnapshotEngineState,
};

export function normalizeSessionStateSnapshot(
  snapshot: SessionStateSnapshot,
): SessionStateSnapshot {
  let normalizedSnapshot = snapshot;

  const runtimeKind =
    snapshot.engineState?.kind
    ?? snapshot.agentRuntimeKind
    ?? (
      snapshot.openAIHistory || snapshot.openAILastResponseId || snapshot.openAIRunState
        ? 'openai-agents-sdk'
        : undefined
    )
    ?? (
      snapshot.sdkSessionId || snapshot.sdkSessionMode
        ? 'claude-agent-sdk'
        : undefined
    );

  if (!snapshot.engineState && runtimeKind) {
    normalizedSnapshot = {
      ...snapshot,
      engineState: PROVIDER_ONLY_ENGINE_STATE[runtimeKind]({
        providerId: snapshot.agentRuntimeProviderId,
        providerSnapshotHash: snapshot.agentRuntimeProviderSnapshotHash,
      }),
    };
  }

  if (
    normalizedSnapshot.sourceUseDecision === undefined &&
    normalizedSnapshot.codeLookupSummary?.sourceUseDecision === undefined
  ) {
    return normalizedSnapshot;
  }
  const {
    sourceUseDecision: rawSourceUseDecision,
    codeLookupSummary: rawCodeLookupSummary,
    ...snapshotWithoutSourceUse
  } = normalizedSnapshot;
  return {
    ...snapshotWithoutSourceUse,
    ...normalizeSourceUseSnapshotFields(
      rawSourceUseDecision,
      rawCodeLookupSummary,
      normalizedSnapshot.codebaseIds ?? [],
    ),
  };
}

// =============================================================================
// SessionStateSnapshot — the core snapshot type
// =============================================================================

/**
 * Unified session state snapshot.
 *
 * Captures all session state needed for:
 * - Atomic persistence (single SQLite metadata UPDATE)
 * - HTML/JSON report generation (no live getter fallback chains)
 * - Session restoration on resume (all ClaudeRuntime Maps + session arrays)
 */
export interface SessionStateSnapshot {
  /** Schema version — enables future format migrations. */
  version: 1;
  /** When this snapshot was taken. */
  snapshotTimestamp: number;
  sessionId: string;
  traceId: string;
  /** Presentation language pinned to this session/runtime conversation. */
  outputLanguage?: OutputLanguage;
  /** Reference trace ID for comparison mode — enables session restoration in dual-trace context */
  referenceTraceId?: string;
  /** Source model for comparison mode. Raw dual-trace sessions use raw_trace_pair. */
  comparisonSource?: ComparisonSourceKind;
  /** Shared deterministic comparison section used by CLI and HTML reports. */
  comparisonReportSection?: ComparisonReportSection;
  /** Final receipt, added explicitly after report/snapshot artifacts settle. */
  analysisReceipt?: import('../types/dataContract').AnalysisReceipt;
  /** Exact current finalized body and metadata; absent for historical snapshots. */
  finalResult?: import('../agent/core/orchestratorTypes').AnalysisResult;
  /** Path-free deterministic Trace Summary attribution for this trace/run. */
  traceSummary?: import('../types/traceSummaryAttribution').TraceSummaryAttributionV1;

  // --- Timeline & History ---
  conversationSteps: ConversationStep[];
  queryHistory: QueryHistoryEntry[];
  conclusionHistory: ConclusionHistoryEntry[];

  // --- Agent Communication ---
  agentDialogue: AgentDialogueEntry[];
  agentResponses: AgentResponseEntry[];

  // --- Data ---
  dataEnvelopes: DataEnvelope[];
  claimSupport?: ClaimSupportV1[];
  claimVerificationResult?: ClaimVerificationResult;
  sourceClaimVerificationResult?: import('../services/codebase/sourceClaimVerifier').StoredSourceClaimVerificationResult;
  identityResolutions?: IdentityResolutionV1[];
  /**
   * Protocol-format hypotheses (from AnalysisResult) for report generation.
   * These use the agentProtocol.Hypothesis shape (id, description, status, confidence).
   */
  hypotheses: any[];

  // --- Claude Runtime State (agentv3-specific) ---
  analysisNotes: AnalysisNote[];
  analysisPlan: AnalysisPlanV3 | null;
  planHistory: AnalysisPlanV3[];
  uncertaintyFlags: UncertaintyFlag[];
  /**
   * agentv3-internal hypotheses (richer than protocol format).
   * Used to restore ClaudeRuntime.sessionHypotheses Map on resume.
   * Contains: id, statement, status, basis, evidence, formedAt, resolvedAt.
   */
  claudeHypotheses?: Hypothesis[];

  // --- Cached Detection ---
  architecture?: ArchitectureInfo;
  /** Canonical engine-local runtime state. Product/report state stays top-level. */
  engineState?: SnapshotEngineState;
  /**
   * Legacy Claude runtime mirrors, no longer written. Still read to infer the
   * runtime kind of snapshots that predate `agentRuntimeKind`/`engineState`.
   */
  sdkSessionId?: string;
  sdkSessionMode?: 'full';

  // --- Backend Runtime State (legacy mirrors; use helpers above for reads) ---
  /** Runtime that produced the snapshot. Omitted for legacy Claude-only snapshots. */
  agentRuntimeKind?: AgentRuntimeKind;
  /**
   * Provider profile that supplied runtime credentials.
   * null means the session is pinned to env/default fallback and must not read
   * the current active Provider Manager profile during restoration.
   */
  agentRuntimeProviderId?: string | null;
  /**
   * Non-secret hash of the provider/runtime configuration that produced the
   * snapshot, compared with the current resolved provider snapshot on restore.
   */
  agentRuntimeProviderSnapshotHash?: string | null;
  /** Append-only audit of provider snapshot changes observed when this session was restored. */
  continuityBreaks?: ProviderContinuityBreak[];
  /** Authorization partition for source/RAG continuation. */
  analysisContextFingerprint?: string;
  /** Immutable public Knowledge Pack identity pinned to this analysis session. */
  androidInternalsPackPin?: import('../services/androidInternalsPack/types').AndroidInternalsPackIdentity;
  /** Public background citations, kept separate from current-trace evidence. */
  backgroundKnowledgeReferences?: import('../types/sparkContracts').BackgroundKnowledgeReference[];
  /** Backend-session ancestry when a user-visible session had to bridge to a fresh backend session. */
  lineage?: SessionLineage;
  /**
   * Legacy OpenAI Agents SDK mirrors, no longer written. Still read to infer the
   * runtime kind of snapshots that predate `agentRuntimeKind`/`engineState`.
   */
  openAIHistory?: unknown[];
  openAILastResponseId?: string;
  openAIRunState?: string;
  /** Code-aware analysis mode persisted with the session. */
  codeAwareMode?: CodeAwareMode;
  /** Explicit codebase allowlist used by this session. */
  codebaseIds?: string[];
  /** Non-secret consent/index-generation state captured for resume/report safety. */
  codebaseSnapshot?: Array<{
    codebaseId: string;
    displayName?: string;
    kind?: import('../services/codebase/codebaseRegistry').CodebaseKind;
    indexGeneration: number;
    activeGeneration?: string;
    contentFingerprint?: string;
    indexedRevision?: string;
    indexedDirty?: boolean;
    commitProvenance?: 'clean_git_revision' | 'dirty_git_worktree' | 'content_only';
    consentHash?: string;
  }>;
  /** Explicit external knowledge allowlist and active provenance for this session. */
  knowledgeSourceIds?: string[];
  knowledgeSourceSnapshot?: Array<{
    sourceId: string;
    indexGeneration: number;
    activeGeneration?: string;
    contentFingerprint: string;
    revision: string;
  }>;
  /** Append-only lookup ledger summary for this session. */
  codeLookupSummary?: CodeLookupSummary;
  /** Canonical privacy-safe decision describing how selected source was used. */
  sourceUseDecision?: SourceUseDecisionV1;

  // --- Artifact Store (optional, can be large) ---
  artifacts?: StoredArtifact[];

  // --- Run Tracking ---
  runSequence: number;
  conversationOrdinal: number;
  activeRun?: SnapshotRunContext;
  lastRun?: SnapshotRunContext;
}

// =============================================================================
// SessionFieldsForSnapshot — what the route layer provides to takeSnapshot()
// =============================================================================

/**
 * Session-level fields provided by the route layer to `takeSnapshot()`.
 *
 * ClaudeRuntime reads its own Maps (notes, plans, flags, artifacts, architecture)
 * internally. The route layer provides the session-scoped arrays
 * that live in the AnalysisSession object.
 */
export interface SessionFieldsForSnapshot {
  /** Presentation language pinned to this session/runtime conversation. */
  outputLanguage?: OutputLanguage;
  /** Reference trace ID for comparison mode session identity. */
  referenceTraceId?: string;
  /** Source model for comparison mode. */
  comparisonSource?: ComparisonSourceKind;
  /** Shared deterministic comparison report section, when available. */
  comparisonReportSection?: ComparisonReportSection;
  analysisReceipt?: SessionStateSnapshot['analysisReceipt'];
  finalResult?: SessionStateSnapshot['finalResult'];
  traceSummary?: SessionStateSnapshot['traceSummary'];
  conversationSteps: ConversationStep[];
  queryHistory: QueryHistoryEntry[];
  conclusionHistory: ConclusionHistoryEntry[];
  agentDialogue: AgentDialogueEntry[];
  agentResponses: AgentResponseEntry[];
  dataEnvelopes: DataEnvelope[];
  claimSupport?: ClaimSupportV1[];
  claimVerificationResult?: ClaimVerificationResult;
  sourceClaimVerificationResult?: SessionStateSnapshot['sourceClaimVerificationResult'];
  identityResolutions?: IdentityResolutionV1[];
  /** Protocol-format hypotheses from AnalysisResult. */
  hypotheses: any[];
  /** Provider profile that supplied runtime credentials for this turn; null means env/default fallback. */
  agentRuntimeProviderId?: string | null;
  /** Non-secret hash of the resolved provider/runtime configuration. */
  agentRuntimeProviderSnapshotHash?: string | null;
  /** Append-only audit of provider snapshot changes observed when this session was restored. */
  continuityBreaks?: ProviderContinuityBreak[];
  analysisContextFingerprint?: string;
  androidInternalsPackPin?: SessionStateSnapshot['androidInternalsPackPin'];
  backgroundKnowledgeReferences?: SessionStateSnapshot['backgroundKnowledgeReferences'];
  /** Backend-session ancestry when a user-visible session had to bridge to a fresh backend session. */
  lineage?: SessionLineage;
  codeAwareMode?: CodeAwareMode;
  codebaseIds?: string[];
  codebaseSnapshot?: SessionStateSnapshot['codebaseSnapshot'];
  knowledgeSourceIds?: string[];
  knowledgeSourceSnapshot?: SessionStateSnapshot['knowledgeSourceSnapshot'];
  codeLookupSummary?: CodeLookupSummary;
  sourceUseDecision?: SourceUseDecisionV1;
  runSequence: number;
  conversationOrdinal: number;
  activeRun?: SnapshotRunContext;
  lastRun?: SnapshotRunContext;
}

/**
 * Private retrieval sessions persist only the verified product result and
 * deterministic trace evidence. Intermediate model-authored state must not be
 * replayable after a restart, regardless of the provider runtime in use.
 */
export function projectSessionFieldsForDurableSnapshot(
  fields: SessionFieldsForSnapshot,
): SessionFieldsForSnapshot {
  if (!analysisHasPrivateContext(fields)) return fields;
  const {
    sourceUseDecision: rawSourceUseDecision,
    codeLookupSummary: rawCodeLookupSummary,
    ...fieldsWithoutSourceUse
  } = fields;
  return {
    ...fieldsWithoutSourceUse,
    ...normalizeSourceUseSnapshotFields(
      rawSourceUseDecision,
      rawCodeLookupSummary,
      fields.codebaseIds ?? [],
    ),
    comparisonReportSection: undefined,
    conversationSteps: [],
    agentDialogue: [],
    agentResponses: [],
    hypotheses: [],
  };
}
